SDUEditor/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from SDUEditor import settings
from App import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SDUEditor.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'file/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.FILE_PATH}),
    url(r'css/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.CSS_PATH}),
    url(r'js/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.JS_PATH}),
    url(r'img/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.IMG_PATH}),
    url(r'^$',views.home),
    url(r'editor/$',views.editor),
    url(r'edit_new$',views.edit_new),
    url(r'^save/$',views.save),
    url(r'^load/$',views.load),
    url(r'^search/$',views.search),
    url(r'^export_(?P<type>.*)/(?P<title>.*)',views.export),
)

App/models.py
from django.db import models

class Record(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=30,verbose_name="书名")
    writer = models.CharField(max_length=10, verbose_name="作者")
    nation = models.CharField(max_length=10, verbose_name="国家/朝代")
    content = models.TextField(verbose_name="内容")
    add_time = models.DateTimeField(verbose_name="添加时间")
    class Meta:
        db_table = "Record"
    def __unicode__(self):
        return self.title

App/forms.py
__author__ = 'andong'

# 已废弃

from django import forms

class AncientBookForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'span3'}),max_length=30,label="书名")
    writer = forms.CharField(widget=forms.TextInput(attrs={'class':'span3'}),max_length=5,label="姓名")
    nation = forms.CharField(widget=forms.TextInput(attrs={'class':'span2'}),max_length=10,label="朝代")
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'area tb-rl'}),label="内容")


class ModernBookForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'span3'}),max_length=30,label="书名")
    writer = forms.CharField(widget=forms.TextInput(attrs={'class':'span3'}),max_length=5,label="姓名")
    nation = forms.CharField(widget=forms.TextInput(attrs={'class':'span2'}),max_length=10,label="国家")
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'area tb-rl'}),label="内容")

App/views.py
from django.shortcuts import render_to_response, redirect
#from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponse
from App import models
from datetime import datetime
import json
from Util import scode, sformat, xmlhelper


def home(request):
    records = models.Record.objects.order_by('-add_time')
    print(records)
    return render_to_response('home.html', {'records':records})

def editor(request):
    return redirect('/file/editor.html')

def load():
    return redirect('/file/editor.html')

def edit_new(request):
    return redirect('file/edit_new.html')

def save(request):
    lst = request.GET
    now = datetime.now()
    models.Record.objects.create(title=lst['title'],writer=lst['writer'],nation=lst['nation'],content=lst['content'],add_time=now)
    xmlhelper.write(request.GET)
    return render_to_response('export.html',{'title':lst['title']})

def search(request):
    if request.method == "GET" and 'side' in request.GET and 'num' in request.GET and 'pinyin' in request.GET:
        side = request.GET['side']
        num = request.GET['num']
        pinyin = request.GET['pinyin']
    response_data = {}
    response_data['status'] = 'OK'
    response_data['char'] = "".join(scode.fetch(side=side, num=num, pinyin=pinyin))
    return HttpResponse(json.dumps(response_data), content_type="application/json")

def export(request, type, title):
    type = type.strip().lower()
    title = title.strip().lower()
    if type=='pdf':
        sformat.exportPDF(title)
    elif type=='image':
        sformat.exportImage(title)
    elif type=='html':
        sformat.exportHTML(title)

templates/dialog.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#btn').click(function(){
                var side = $('#side').val();
                var num = $('#num').val();
                var pinyin = $('#pinyin').val();
               $.get('/search/',{'side':side, 'num':num, 'pinyin':pinyin}, function(data){
                   var result = data.char;
                    $('#result').val(result);
                });
            });
        });
    </script>
</head>
<body>
偏旁<input id="side" name="side"><br>
笔画数<input id="num" name="pinyin"><br>
拼音<input id="pinyin" name="pinyin"><br>
<button id="btn">查询</button>
<br/>
结果：<input id="result">
</body>
</html>

templates/edit_new.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8"/>
    <title>现代文编辑器</title>
    <link href="css/layout.css" rel="stylesheet" type="text/css"/>
    <link href="http://twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css"
          rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css"
          rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://mindmup.s3.amazonaws.com/lib/jquery.hotkeys.js"></script>
    <script src="http://cdn.bootcss.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
    <script src="js/bootstrap-wysiwyg.js"></script>
    <script>
        $(function () {
            function initToolbarBootstrapBindings() {
                var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier',
                            'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
                            'Times New Roman', 'Verdana'],
                        fontTarget = $('[title=Font]').siblings('.dropdown-menu');
                $.each(fonts, function (idx, fontName) {
                    fontTarget.append($('<li><a data-edit="fontName ' + fontName + '" style="font-family:\'' + fontName + '\'">' + fontName + '</a></li>'));
                });
                $('a[title]').tooltip({container: 'body'});
                $('.dropdown-menu input').click(function () {
                    return false;
                })
                        .change(function () {
                            $(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle');
                        })
                        .keydown('esc', function () {
                            this.value = '';
                            $(this).change();
                        });

                $('[data-role=magic-overlay]').each(function () {
                    var overlay = $(this), target = $(overlay.data('target'));
                    overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
                });
            };
            initToolbarBootstrapBindings();
            $('#editor').wysiwyg();
            window.prettyPrint && prettyPrint();
        });
    </script>
</head>
<body>
<div class="container">
    <div class="page-header">
        <h1>现代文编辑器</h1>
    </div>
    <div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
            <div class="btn-group">
                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="icon-font"></i><b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                </ul>
            </div>
            <div class="btn-group">
                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="icon-text-height"></i>&nbsp;<b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
                    <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
                    <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
                </ul>
            </div>
            <div class="btn-group">
                <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
                <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
                <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
                <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
            </div>
            <div class="btn-group">
                <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
                <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
                <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
                <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
            </div>
            <div class="btn-group">
                <a class="btn" data-edit="justifyleft" title="Align Top (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
                <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
                <a class="btn" data-edit="justifyright" title="Align Down (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
                <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
            </div>

            <div class="btn-group">
                <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
                <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
            </div>

            <div class="btn-group">
                <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
            </div>
        </div>
    <form action="/save/" method="get">

        <div id="editor" name="content" class="area lr-tb" contenteditable="true"></div>
        <div class="control-group">
            <label class="control-label" for="id_title">书名</label>

            <div class="controls">
                <input id="title" name="title" class="span3" required>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_name">作者</label>

            <div class="controls">
                <input id="writer" name="writer" class="span3" required>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_nation">国家</label>

            <div class="controls">
                <input id="nation" name="nation" class="span2" required>
            </div>
        </div>
        <button class="btn btn-info btn-large"><a href="/save" style="text-decoration:none">保存</a></button>
    </form>
</div>
</body>
</html>

templates/editor.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8"/>
    <title>古文编辑器</title>
    <link href="css/layout.css" rel="stylesheet" type="text/css"/>
    <link href="http://twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.no-icons.min.css"
          rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css"
          rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://mindmup.s3.amazonaws.com/lib/jquery.hotkeys.js"></script>
    <script src="http://cdn.bootcss.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
    <script src="js/bootstrap-wysiwyg.js"></script>
    <script>
        $(function () {
            function initToolbarBootstrapBindings() {
                var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier',
                            'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
                            'Times New Roman', 'Verdana'],
                        fontTarget = $('[title=Font]').siblings('.dropdown-menu');
                $.each(fonts, function (idx, fontName) {
                    fontTarget.append($('<li><a data-edit="fontName ' + fontName + '" style="font-family:\'' + fontName + '\'">' + fontName + '</a></li>'));
                });
                $('a[title]').tooltip({container: 'body'});
                $('.dropdown-menu input').click(function () {
                    return false;
                })
                        .change(function () {
                            $(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle');
                        })
                        .keydown('esc', function () {
                            this.value = '';
                            $(this).change();
                        });

                $('[data-role=magic-overlay]').each(function () {
                    var overlay = $(this), target = $(overlay.data('target'));
                    overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
                });
            };
            initToolbarBootstrapBindings();
            $('#editor').wysiwyg();
            window.prettyPrint && prettyPrint();
        });
        $(document).ready(function(){
           $('#btn').click(function(){
                $('#content').val($('#editor').html())
           });
        });
    </script>
    <script>
        $(document).ready(function(){
            $('#dialog_link').click(function () {
                window.open ('dialog.html', 'newwindow', 'height=200, width=400, top=0, left=0, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=n o, status=no')
});
        })
    </script>
</head>
<body>
<div class="container">
    <div class="page-header">
        <h1>古文编辑器</h1>
    </div>
    <div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
            <div class="btn-group">
                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="icon-font"></i><b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                </ul>
            </div>
            <div class="btn-group">
                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="icon-text-height"></i>&nbsp;<b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a data-edit="fontSize 7"><font size="7">Huge</font></a></li>
                    <li><a data-edit="fontSize 5"><font size="5">Big</font></a></li>
                    <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
                    <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
                </ul>
            </div>
            <div class="btn-group">
                <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
                <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
                <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
                <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
            </div>
            <div class="btn-group">
                <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
                <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
                <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
                <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
            </div>
            <div class="btn-group">
                <a class="btn" data-edit="justifyleft" title="Align Top (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
                <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
                <a class="btn" data-edit="justifyright" title="Align Down (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
                <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
            </div>

            <div class="btn-group">
                <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
                <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
            </div>

            <div class="btn-group">
                <a id="dialog_link" class="btn" title="insert Character"><i class="icon-plus"></i></a>
            </div>

        </div>
    <form action="/save/" method="get">
        <input id="content" name="content" type="hidden">
        <div id="editor" class="area tb-rl" contenteditable="true"></div>
        <div class="control-group">
            <label class="control-label" for="id_title">书名</label>

            <div class="controls">
                <input id="title" name="title" class="span3" required>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_name">作者</label>

            <div class="controls">
                <input id="writer" name="writer" class="span3" required>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_nation">朝代</label>

            <div class="controls">
                <input id="nation" name="nation" class="span2" required>
            </div>
        </div>
        <button id="btn" class="btn btn-info btn-large" type="submit">保存</button>
    </form>
</div>
</body>
</html>

templates/export.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}保存成功！</title>
</head>
<body>
<strong>《{{ title }}》保存成功！</strong>
<button><a href="/export_pdf/{{ title }}">导出PDF</a></button>
<button><a href="/export_image/{{ title }}">导出图像</a></button>
<button><a href="/export_html/{{ title }}">导出网页</a></button>
<br/><a href="/">返回首页</a>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>主页</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/mycss.css" rel="stylesheet">
    <script src="js/bootstrap.js"></script>
    <script src="js/jquery-2.0.3.js"></script>

</head>
<body>

<div class="jumbotron masthead" style="margin-top: -20px">
    <div class="container">
        <h1>SDUEditor</h1>

        <p>所见即所得的书籍数字化编辑器</p>
    </div>
</div>

<div class="container">
    <div class="page-header">
        <h1>创建...</h1>
        <button class="btn btn-info btn-large"><a href="/edit_new" style="text-decoration:none">创建现代文</a></button>
        <button class="btn btn-info btn-large"><a href="/editor" style="text-decoration:none">创建古文</a></button>
    </div>
    <div class="page-header">
        <h1>打开...</h1>
        <input type="file" name="file" id="file">
        <button class="btn btn-info btn-large"><a href="/editor" style="text-decoration:none">导入sDOC</a></button>
    </div>

    <div class="page-header">
        <h2>历史记录</h2>
        <ul class="wrap">
        {% for record in records %}
        <li class="item">
            <div class="cover">
                <img width="70px" height="100px" src="/img/images.jpg">
            </div>
            <div class="info">
                <p>书名：{{ record.title }}</p>
                <p>作者：{{ record.writer }}</p>
                <p>国家/朝代：{{ record.nation }}</p>
                <p>添加日期：{{ record.add_time }}</p>
            </div>
        </li>
        {% endfor %}
        </ul>
    </div>

</div>
</body>
</html>